//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Api.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStoreMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStoreMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppStore.Api.Language.AppStoreMsg", typeof(AppStoreMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF0001 - User created successfully.
        /// </summary>
        public static string INF0001 {
            get {
                return ResourceManager.GetString("INF0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF0003 - Error querying available applications.
        /// </summary>
        public static string INF0003 {
            get {
                return ResourceManager.GetString("INF0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF0004 - The application has been registered.
        /// </summary>
        public static string INF0004 {
            get {
                return ResourceManager.GetString("INF0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF0006 - Purchase made successfully.
        /// </summary>
        public static string INF0006 {
            get {
                return ResourceManager.GetString("INF0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF0008 - Some input parameter is incorrect.
        /// </summary>
        public static string INF0008 {
            get {
                return ResourceManager.GetString("INF0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF0009 - There is no user with TaxNumber {0}.
        /// </summary>
        public static string INF0009 {
            get {
                return ResourceManager.GetString("INF0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF0010 - Code {0} for application does not exist.
        /// </summary>
        public static string INF0010 {
            get {
                return ResourceManager.GetString("INF0010", resourceCulture);
            }
        }
    }
}
